name: oasis
version: 0.1.0
publish_to: "none"
description: Employee management app (Flutter)
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
