openapi: 3.0.0
info:
  title: Expense Service API
  version: 1.0.0
servers:
  - url: http://localhost:4003
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  service:
                    type: string
  /expense:
    post:
      summary: Submit an expense
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: ID of the user submitting the expense
                amount:
                  type: number
                  description: Amount of the expense
                date:
                  type: string
                  format: date
                  description: Date of the expense
                description:
                  type: string
                  description: Description of the expense
                receipt:
                  type: string
                  format: binary
                  description: Receipt file upload
              required:
                - userId
                - amount
                - date
                - description
      responses:
        '200':
          description: Expense submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Expense:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        amount:
          type: number
        description:
          type: string
        date:
          type: string
          format: date
        receipt:
          type: string
          description: Path to uploaded receipt file
