openapi: 3.0.0
info:
  title: Oasis Timesheet API
  version: 1.0.0
servers:
  - url: http://localhost:4000
paths:
  /timesheet:
    post:
      summary: Submit timesheet entry/exit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimesheetEntry'
      responses:
        '200':
          description: Timesheet submitted
    get:
      summary: Get timesheet entries
      responses:
        '200':
          description: List of timesheet entries
  /approval:
    post:
      summary: Approve or reject timesheet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApprovalRequest'
      responses:
        '200':
          description: Approval processed
components:
  schemas:
    TimesheetEntry:
      type: object
      properties:
        userId:
          type: string
        action:
          type: string
          enum: [entry, exit]
        timestamp:
          type: string
          format: date-time
        device:
          $ref: '#/components/schemas/DeviceInfo'
        location:
          $ref: '#/components/schemas/LocationInfo'
    DeviceInfo:
      type: object
      properties:
        type:
          type: string
          enum: [desktop, laptop, tablet, mobile]
        os:
          type: string
        deviceId:
          type: string
    LocationInfo:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
        address:
          type: string
    ApprovalRequest:
      type: object
      properties:
        timesheetId:
          type: string
        approved:
          type: boolean
        adminId:
          type: string
        comment:
          type: string
