openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
servers:
  - url: http://localhost:4001
paths:
  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
  /auth/logout:
    post:
      summary: Logout user
      responses:
        '200':
          description: Logout successful
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
