openapi: 3.0.0
info:
  title: Device Service API
  version: 1.0.0
servers:
  - url: http://localhost:4104
paths:
  /devices:
    get:
      summary: Get all devices
      responses:
        '200':
          description: List of devices
    post:
      summary: Register a new device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '201':
          description: Device registered
  /devices/{id}:
    get:
      summary: Get device by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device details
components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        status:
          type: string
